### ISSUE TITLE
React Router issue and keeping up with browser history when clicking the in-browser back button.

### ISSUE THREAD

**Issue by tankisoDev** [majortank/pathpioneer#1]
I can navigate from landing page to login and login to register but I can not go back to landing page from login page.

**Comment by Sky-De** [comment]
@majortank please assign this to me, i would like to work on this
Thanks

**Comment by majortank** [comment]
@Sky-De Thanks, just assigned it to you. sorry for the delay.

**Comment by majortank** [comment]
Issue has been resolved by @fiorenzo84 . Thank you all.
